### ISSUE TITLE
是否需要将 modules/generation_utils.p覆盖掉transformers/generation_utils.py？

### ISSUE THREAD

**Issue by ChenKefei** [LeMei/UniMSE#11]
在modules/modeling_t5.py  modeling_t5_prefix.py等文件里，您重写了_prepare_encoder_decoder_kwargs_for_generation函数（使用self._prepare_encoder_decoder_kwargs_for_generation调用），但代码input_ids = self._prepare_decoder_input_ids_for_generation(input_ids, decoder_start_token_id=decoder_start_token_id, bos_token_id=bos_token_id) 仍会调用transformers/generation_utils.py里的_prepare_decoder_input_ids_for_generation【备注：其中第一个参数应为int型的batchsize】。我看到您在modules/generation_utils.py里将该函数的第一个参数改为了longtensor型【备注：符合input_ids的类型】，但modules/modeling_t5.py文件并没有使用modules/generation_utils.py而是使用了默认的transformers/generation_utils.py。
也就是运行代码时，会因为调用的函数参数类型不一致报错，请问我该如何修改使之适配呢？
非常感谢！

**Comment by LeMei** [comment]
感谢您对我们工作的关注~
会报错嘛？之前没遇到过
注意下Transformer的版本，尽可能使用我在README中指明的版本。
您可以给我截下图，我看下您这个问题出现的位置。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LeMei/UniMSE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月1日(星期三) 晚上7:41
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[LeMei/UniMSE] 是否需要将 modules/generation_utils.p覆盖掉transformers/generation_utils.py？ (Issue #11)





 
在modules/modeling_t5.py  modeling_t5_prefix.py等文件里，您重写了_prepare_encoder_decoder_kwargs_for_generation函数（使用self._prepare_encoder_decoder_kwargs_for_generation调用），但代码input_ids = self._prepare_decoder_input_ids_for_generation(input_ids, decoder_start_token_id=decoder_start_token_id, bos_token_id=bos_token_id) 仍会调用transformers/generation_utils.py里的_prepare_decoder_input_ids_for_generation【备注：其中第一个参数应为int型的batchsize】。我看到您在modules/generation_utils.py里将该函数的第一个参数改为了longtensor型【备注：符合input_ids的类型】，但modules/modeling_t5.py文件并没有使用modules/generation_utils.py而是使用了默认的transformers/generation_utils.py。
 也就是运行代码时，会因为调用的函数参数类型不一致报错，请问我该如何修改使之适配呢？
 非常感谢！

**Comment by ChenKefei** [comment]
![image](https://user-images.githubusercontent.com/42538640/222322329-ce04ba9f-25bc-4c14-afc3-8eb58948fc3d.png)

**Comment by LeMei** [comment]
completed
