### ISSUE TITLE
Do I need to download both BaiDu and Google Drive link?

### ISSUE THREAD

**Issue by Myrrolinz** [LeMei/UniMSE#13]
两个链接内容是一样的吗？为什么我看见文件名是一样大的，但是文件大小不同？
非常感谢您的解答。

**Comment by LeMei** [comment]
> 两个链接内容是一样的吗？为什么我看见文件名是一样大的，但是文件大小不同？ 非常感谢您的解答。

您指的哪个文件大小不一致呢，四个数据集的特征在两个上是一样的，如果是文本信息可能是我压缩的方式不同导致的。
您可以只选择下载一个。祝好

**Comment by Myrrolinz** [comment]
> 

ok thank you very much 😸
