### ISSUE TITLE
No such file or directory: 't5-large/pytorch_model.bin'

### ISSUE THREAD

**Issue by KindredSpirithub** [LeMei/UniMSE#15]
请问一下pytorch_model.bin这个文件是需要自己在哪里下载吗？

**Comment by LeMei** [comment]
> 请问一下pytorch_model.bin这个文件是需要自己在哪里下载吗？

可以在https://huggingface.co/上找到T5模型相应下载

**Comment by KindredSpirithub** [comment]
好的，已经解决，感谢

**Comment by Myrrolinz** [comment]
@KindredSpirithub 请问您下载的是哪一个，可以分享一下过程吗？我也遇到了这个问题。

**Comment by JuneHou** [comment]
> > 请问一下pytorch_model.bin这个文件是需要自己在哪里下载吗？
> 
> 可以在[https://huggingface.co/上找到T5模型相应下载](https://huggingface.co/%E4%B8%8A%E6%89%BE%E5%88%B0T5%E6%A8%A1%E5%9E%8B%E7%9B%B8%E5%BA%94%E4%B8%8B%E8%BD%BD)

Where can I find the checkpoint required? Or I can just remove that code, just use the t5 downloaded from huggingface?
