### ISSUE TITLE
如何使用这些文件

### ISSUE THREAD

**Issue by Myrrolinz** [LeMei/UniMSE#18]
![image](https://user-images.githubusercontent.com/70125231/229731324-71d9d568-530d-4939-8702-ff9e94e5ab92.png)
您好，我在复现论文的时候遇到了一些问题：
1. 请问Sim_Process_v3中的这些文件可以从哪里找到？Restaurants和Laptops又是什么？
2. 您提供的pickle文件又该如何使用呢？
期待您的回复，感激不尽！

**Comment by Cosmos-Break** [comment]
某些数据在text.zip文件里面，但是没有Restaurants和Laptops。
同样求助如何复现。

**Comment by flow-ljh** [comment]
+1

**Comment by Myrrolinz** [comment]
> 某些数据在text.zip文件里面，但是没有Restaurants和Laptops。 同样求助如何复现。

我已经复现了，作者已经把处理完的文件给出来了，Sim_Process_v3似乎是不用run的。只要跑src里的预处理就好，自己把0242和0610文件名改一下就行。

**Comment by flow-ljh** [comment]
> > 某些数据在text.zip文件里面，但是没有Restaurants和Laptops。 同样求助如何复现。
> 
> 我已经复现了，作者已经把处理完的文件给出来了，Sim_Process_v3似乎是不用run的。只要跑src里的预处理就好，自己把0242和0610文件名改一下就行。

Hi~,thanks for your reply.Can u tell me your reproduce result and specific method?I try your method but still have some problems.I will appreciate your help.

**Comment by Myrrolinz** [comment]
> > > 某些数据在text.zip文件里面，但是没有Restaurants和Laptops。 同样求助如何复现。
> > 
> > 
> > 我已经复现了，作者已经把处理完的文件给出来了，Sim_Process_v3似乎是不用run的。只要跑src里的预处理就好，自己把0242和0610文件名改一下就行。
> 
> Hi~,thanks for your reply.Can u tell me your reproduce result and specific method?I try your method but still have some problems.I will appreciate your help.

Sorry for late reply, just run preprocess.py and create_dataset.py. If you meet an error you can paste a screenshot here? Hope it will work for you.

**Comment by GOSkype** [comment]
你好请问用的是python的哪个版本？

**Comment by GOSkype** [comment]
> > > > 某些数据在text.zip文件里面，但是没有Restaurants和Laptops。 同样求助如何复现。
> > > 
> > > 
> > > 我已经复现了，作者已经把处理完的文件给出来了，Sim_Process_v3似乎是不用run的。只要跑src里的预处理就好，自己把0242和0610文件名改一下就行。
> > 
> > 
> > Hi~,thanks for your reply.Can u tell me your reproduce result and specific method?I try your method but still have some problems.I will appreciate your help.
> 
> Sorry for late reply, just run preprocess.py and create_dataset.py. If you meet an error you can paste a screenshot here? Hope it will work for you.

请问用的是python的哪个版本

**Comment by LeMei** [comment]
统一回复下，Restaurants和Laptops在我们论文中并没有使用，因此没有提供相关数据。
代码中有是之前有尝试将Restaurants和Laptops也统一到模型中，但效果不理想，因此并没有使用这两个数据集。

**Comment by GOSkype** [comment]
那么是可以在代码中吧这两个数据集的代码段删除嘛

**Comment by GOSkype** [comment]
> 统一回复下，Restaurants和Laptops在我们论文中并没有使用，因此没有提供相关数据。 代码中有是之前有尝试将Restaurants和Laptops也统一到模型中，但效果不理想，因此并没有使用这两个数据集。

那么是可以在代码中吧这两个数据集的代码段删除嘛

**Comment by LeMei** [comment]
> > 统一回复下，Restaurants和Laptops在我们论文中并没有使用，因此没有提供相关数据。 代码中有是之前有尝试将Restaurants和Laptops也统一到模型中，但效果不理想，因此并没有使用这两个数据集。
> 
> 那么是可以在代码中吧这两个数据集的代码段删除嘛

对的，可以注释掉

**Comment by GOSkype** [comment]
> > > 统一回复下，Restaurants和Laptops在我们论文中并没有使用，因此没有提供相关数据。 代码中有是之前有尝试将Restaurants和Laptops也统一到模型中，但效果不理想，因此并没有使用这两个数据集。
> > 
> > 
> > 那么是可以在代码中吧这两个数据集的代码段删除嘛
> 
> 对的，可以注释掉
![image](https://user-images.githubusercontent.com/39805002/235825208-0a83a2a5-2c4c-4410-a42f-58dbbb9c31d6.png)
请问这个问题怎么解决，找不到这个pkl文件

**Comment by LeMei** [comment]
这是可以将文件名改成相应的0610.pkl的版本

**Comment by GOSkype** [comment]
> 这是可以将文件名改成相应的0610.pkl的版本

![image](https://user-images.githubusercontent.com/39805002/235827089-c9845e82-099c-4410-921f-33035ecfacaa.png)
似乎还是不行，这个pkl文件是代码中生成的呢还是原来就有这个文件的呢

**Comment by LeMei** [comment]
https://pan.baidu.com/s/190tw6g0bPkiOPu5xPpvDTQ
你可以配置下路径

**Comment by GOSkype** [comment]
> https://pan.baidu.com/s/190tw6g0bPkiOPu5xPpvDTQ 你可以配置下路径

![image](https://user-images.githubusercontent.com/39805002/235831405-3c70e3b6-7a9c-435a-a4b8-fd4447b1ad2b.png)
请问这个cuo错误是什么原因呢

**Comment by GOSkype** [comment]
> > https://pan.baidu.com/s/190tw6g0bPkiOPu5xPpvDTQ 你可以配置下路径
> 
> ![image](https://user-images.githubusercontent.com/39805002/235831405-3c70e3b6-7a9c-435a-a4b8-fd4447b1ad2b.png) 请问这个cuo错误是什么原因呢

![image](https://user-images.githubusercontent.com/39805002/235832265-a67f33f4-644f-4a70-97ca-bf259376c066.png)
这个sklearn包的版本有要求嘛？

**Comment by GOSkype** [comment]
> https://pan.baidu.com/s/190tw6g0bPkiOPu5xPpvDTQ 你可以配置下路径

请问一下，复现这个代码，请问要运行哪些代码文件，运行的顺序是什么呢？能麻烦您回答一下嘛，谢谢

**Comment by HandsomeCBX** [comment]
> > https://pan.baidu.com/s/190tw6g0bPkiOPu5xPpvDTQ 你可以配置下路径
> 
> 请问一下，复现这个代码，请问要运行哪些代码文件，运行的顺序是什么呢？能麻烦您回答一下嘛，谢谢

数据集我怎么下载不了，怎么下载数据集

**Comment by HandsomeCBX** [comment]
> > 某些数据在text.zip文件里面，但是没有Restaurants和Laptops。 同样求助如何复现。
> 
> 我已经复现了，作者已经把处理完的文件给出来了，Sim_Process_v3似乎是不用run的。只要跑src里的预处理就好，自己把0242和0610文件名改一下就行。

具体步骤是什么呢，可以添加联系方式告知一下吗，谢谢

**Comment by HandsomeCBX** [comment]
> Author

可以加个联系方式讲讲怎么复现的吗，我总是复现不成功，qq1040907597，谢谢

**Comment by wuxy07** [comment]
> > 某些数据在text.zip文件里面，但是没有Restaurants和Laptops。 同样求助如何复现。
> 
> 我已经复现了，作者已经把处理完的文件给出来了，Sim_Process_v3似乎是不用run的。只要跑src里的预处理就好，自己把0242和0610文件名改一下就行。

I have a KeyError problem in preprocess.py, could you please tell me how to solve this problem, thanks!
![image](https://github.com/LeMei/UniMSE/assets/102654855/358cfffb-8469-4ebb-9d5c-722c137cd1c3)
@Myrrolinz

**Comment by woaixnn** [comment]
> > > https://pan.baidu.com/s/190tw6g0bPkiOPu5xPpvDTQ你可以配置下路径
> > 
> > 
> > ![图像](https://user-images.githubusercontent.com/39805002/235831405-3c70e3b6-7a9c-435a-a4b8-fd4447b1ad2b.png)请问这个cuo错误是什么原因呢
> 
> ![图像](https://user-images.githubusercontent.com/39805002/235832265-a67f33f4-644f-4a70-97ca-bf259376c066.png) 这个sklearn包的版本有要求嘛？

解决了吗

**Comment by ZMM959** [comment]
> > > 某些数据在text.zip文件里面，但是没有Restaurants和Laptops。同样求助如何复现。
> > 
> > 
> > 我已经复现了，作者已经把处理完的文件给出来了，Sim_Process_v3似乎是不用run的。只要跑src里的预处理就好，自己把0242和0610文件名改一下就行。
> 
> 我 preprocess.py 有一个 KeyError 问题，您能告诉我如何解决这个问题吗，谢谢！ ![图像](https://private-user-images.githubusercontent.com/102654855/287573190-358cfffb-8469-4ebb-9d5c-722c137cd1c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MDYwODUsIm5iZiI6MTcyODcwNTc4NSwicGF0aCI6Ii8xMDI2NTQ4NTUvMjg3NTczMTkwLTM1OGNmZmZiLTg0NjktNGViYi05ZDVjLTcyMmMxMzdjZDFjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQwNDAzMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYWQyNTgxY2VlZjU0NDMzY2IyMTUzMWM5MjMyYzI2ODlmZDMzMjVjNThhMzY5ZDBkYmVhYzgwM2FjNGRhNTM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ncjaZFMqyqU-V-8yQ7QhQB_uc4mYiN375zfApwAgxzU)

我也有这个问题 请问是什么原因
