### ISSUE TITLE
关于Adapter层（多模态融合层）

### ISSUE THREAD

**Issue by yenanjing** [LeMei/UniMSE#23]
您好，请问文章中将多模态融合层同时嵌入到编码器和解码器的设计原因是什么呢？如果仅将多模态层加入到编码器，效果是不如同时在编码器和解码器中吗？
感谢！

**Comment by LeMei** [comment]
> 您好，请问文章中将多模态融合层同时嵌入到编码器和解码器的设计原因是什么呢？如果仅将多模态层加入到编码器，效果是不如同时在编码器和解码器中吗？ 感谢！

感谢关注～
1. 当时的出发点是因为UniMSE作为一个生成任务，希望能通过在decoder部分将模态融合直接影响生成的训练。
2. 有做相关实验，效果在MOSI, MOSEI略差。
