### ISSUE TITLE
配置环境问题

### ISSUE THREAD

**Issue by JIaqiYang78** [LeMei/UniMSE#25]
Hello,

在您的Readme文件里即提到了用pytorch1.7又有用tensorflow-gpu，所以是这两个环境都需要安装吗？还是二选一呢？Tensorflow的版本可以是2.0吗？

**Comment by LeMei** [comment]
可以的

**Comment by JIaqiYang78** [comment]
> 可以的

sorry,我想问一下pytorch和tensorflow都要装吗，不安装tensorflow可以吗
