### ISSUE TITLE
How do you set up the training and validation sets?

### ISSUE THREAD

**Issue by qftie** [LeMei/UniMSE#3]
I noticed that you claim: 
> We integrate the training sets of MOSI,MOSEI, MELD, IEMOCAP to train the model and valid sets to select hyperparameters.

Did you fuse all the datasets into one training set, and did you use the same model weights on four benchmark reviews? 
And did you also fuse the valid sets to get 1 best model for all 4 datasets?

**Comment by LeMei** [comment]
Yes, we fuse all the datasets into one training set and use the same model weights on four benchmark reviews.

We also fuse the valid sets to get 1 best model for all 4 datasets.
