### ISSUE TITLE
'../datasets/Laptops/all_convert.json' not found

### ISSUE THREAD

**Issue by SWXxing** [LeMei/UniMSE#38]
![image](https://github.com/LeMei/UniMSE/assets/129766795/1de17670-0e73-418a-b869-6dd4b6efb18c)

**Comment by woaixnn** [comment]
Have you solved this problem?

**Comment by woaixnn** [comment]
FileNotFoundError: [Errno 2] No such file or directory: '../datasets/Laptops/all_convert.json'

**Comment by DeligentZ** [comment]
Hello, I meet the same problem with you, and may I ask you about have you solve the problem?
