### ISSUE TITLE
我把pickle 的keys 做了个输出，没有 0，1，2 可以解释下吗，感谢

### ISSUE THREAD

**Issue by woaixnn** [LeMei/UniMSE#45]

**Comment by woaixnn** [comment]
是在preprocess.py中的一个问题，emotion_features加载了pickle文件，然后在执行这条语句（train_emotion_f, dev_emotion_f, test_emotion_f = Emotion_features[0], Emotion_features[1], Emotion_features[2]）的这时会报KeyError:0的错误。当我尝试输入emotion_features的按键时，发现只有音频和视频，不是0、1、2。结果如图所示。

![image](https://github.com/LeMei/UniMSE/assets/115681275/da018f32-029f-4759-83a0-b3c6f1b1736b)

**Comment by woaixnn** [comment]
![image](https://github.com/LeMei/UniMSE/assets/115681275/4657db9b-397e-4d65-a415-c772f382919c)

**Comment by LeMei** [comment]
抱歉影响了您的工作，可以和我具体说下吗，我不太记得了...

**Comment by wuxy07** [comment]
> 抱歉影响了您的工作，可以和我具体说下吗，我不太记得了...

是在preprocess.py中的一个问题，emotion_features加载了pickle文件，然后在执行这个语句（train_emotion_f, dev_emotion_f, test_emotion_f = emotion_features[0], emotion_features[1], emotion_features[2]）的时候会报KeyError:0的错误。当我尝试输出emotion_features的keys时，发现只有audio和video，并不是0、1、2。

**Comment by woaixnn** [comment]
是在preprocess.py中的一个问题，emotion_features加载了pickle文件，然后在执行这个语句（train_emotion_f, dev_emotion_f, test_emotion_f =情感_features[0],情感_features[1],情感_features[2]）的时候会报KeyError:0的错误。当我尝试输入emotion_features的按键时，发现只有音频和视频，不是0、1、2。而且我发现在另一个文件中处理同一个pickle文件的读取方式不一样。一个是data[0],一个是data['audio'][0],感谢您的回应

**Comment by togetaname** [comment]
请问这个问题解决了吗

**Comment by ZMM959** [comment]
请问这个问题解决了吗
