### ISSUE TITLE
按照readme执行main.py 发生错误，错误如下。能否解答一下，感谢

### ISSUE THREAD

**Issue by woaixnn** [LeMei/UniMSE#46]
FileNotFoundError: [Errno 2] No such file or directory: '/home/dwh/unimse/datasets/MOSELDMP/new_moseldmp_train_align_v4_0424_a_6c_contexts.pkl'

提示没有new_moseldmp_train_align_v4_0424_a_6c_contexts.pkl文件，我没找到生成此文件的代码

**Comment by LeMei** [comment]
感谢关注～
您直接替换其0624.pk的文件即可
想问下，您上个提的issue是什么造成的，我现在没有运行环境。

**Comment by woaixnn** [comment]
是在preprocess.py中的一个问题，emotion_features加载了pickle文件，然后在执行这个语句
（train_emotion_f, dev_emotion_f, test_emotion_f = emotion_features[0], emotion_features[1],emotion_features[2]）
的时候会报KeyError:0的错误。

我查看的是你的pickle文件读取出来的里面存的是map格式的emotion_feature，就输出key，按照代码应当输出 0，1，2。但是当我执行输出时,输出的是dict_keys(['audio', 'video'])。我看到您在别的而且我发现在另一个文件中处理同一个pickle文件的读取方式不一样。一个是emotion_features[0],一个是emotion_feature['audio'][0],当我将代码改成

train_emotion_f, dev_emotion_f, test_emotion_f = emotion_features['audio'][0], emotion_features['audio'][1],emotion_features['audio'][2]

程序运行了，输出结果如下：

0_0
0_1
0_2
0_3
0_4
0_5
0_6

**Comment by LeMei** [comment]
好的，感谢您的回复~

**Comment by woaixnn** [comment]
我看到在data_processor.py 中有
![image](https://github.com/LeMei/UniMSE/assets/115681275/de0876f1-8ab4-4ea7-a260-eb1ec560a0e1)
生成我所需要执行main.py文件提示错误需要的文件类似的文件生成，是不是我要现运行data_processor.py文件，然后再执行main.py文件？感谢回复~~

**Comment by woaixnn** [comment]
如果能顺利执行成功的话，我会将我的执行过程写一份详细的readme。感谢~~~

**Comment by LeMei** [comment]
是这样子，已经将最终生成的文件放在google drive，可以不用生成。
data_processor.py的文件可以按需生成。。
在前期的工作中，做过大量尝试，比如只用mosi,mosei和iemocap生成对应数据集
或者是将mosi,mosei的上下文考虑进来，这些文件都属于探索的血光工作。

**Comment by LeMei** [comment]
非常感谢～也抱歉写的readme不够详细

> 如果能顺利执行成功的话，我会将我的执行过程写一份详细的readme。感谢~~~

**Comment by woaixnn** [comment]
好的，感谢~~~~~
