### ISSUE TITLE
请问Laptops在哪里下载

### ISSUE THREAD

**Issue by DeligentZ** [LeMei/UniMSE#49]
您好，感谢您的代码贡献。
我在运行Sim_Process_v3.py时遇到了问题；
提示找不到Laptops/all_convert.json;
请问这个文件在哪里下载呢，感谢您的帮助。

**Comment by 1239110565** [comment]
你好,请问找到这个文件了吗,我也遇到了同样的问题

**Comment by pingjm** [comment]
+1

**Comment by 1239110565** [comment]
作者在其他的issue中提到了这个解决方案

**Comment by LeMei** [comment]
感谢您的关注，并不需要Laptops数据集，直接注释掉即可
