### ISSUE TITLE
Link to features is expired

### ISSUE THREAD

**Issue by abdifatah87** [LeMei/UniMSE#7]
Hi, I wanted to access the features for the different datasets, but the link says it is expired. Is it possible to make them available again? Thank you.

**Comment by LeMei** [comment]
I have updated the link.


best wishes




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LeMei/UniMSE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月4日(星期六) 晚上7:29
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[LeMei/UniMSE] Link to features is expired (Issue #7)





 
Hi, I wanted to access the features for the different datasets, but the link says it is expired. Is it possible to make them available again? Thank you.

**Comment by abdifatah87** [comment]
Hi again, I see that you have made the features available via baidu and was wondering if it is possible to share the data via Google drive since I'm having issues with baidu services.
